name: Rust

on:
  push:
    branches: ["main"]
    paths:
      - "**.rs"
      - "**.toml"
      - "flake.**"
      - ".github/workflows/rust.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "**.rs"
      - "**.toml"
      - "flake.**"
      - ".github/workflows/rust.yaml"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    needs: [test]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace: ["pmdrcntr-api", "pmdrcntr"]

    steps:
      # Prereqs
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      # Caching

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      # Build

      - name: Build
        run: nix build .#${{ matrix.workspace }}-dev

      # Caching
      
      # TODO: re-enable when I find a way to fix the error with nix bundle complaining
      # about the output not being a derivation
      #- name: Upload Build Artifact
      #  uses: actions/upload-artifact@v3.1.2
      #  with:
      #    name: x86_64-linux-debug-${{ matrix.workspace }}
      #    path: ./target/debug/${{ matrix.workspace }}

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        workspace: ["pmdrcntr-api", "pmdrcntr", "pomolib"]

    steps:
      # Prereq
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      # Caching

      - name: Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v2

      # Run

      - name: Run tests
        run: nix develop .#rust --impure --command bash -c "cargo test -p ${{ matrix.workspace }} --verbose"

      # Caching

      - name: Save rust target
        uses: actions/cache/save@v3
        with:
          path: |
            ./target
            ~/.cargo
          key: ${{ steps.cache-rust-restore.outputs.cache-primary-key }}
